from .user import User
from .student import Student
from .teacher import Teacher
from .department import Department
from .classroom import Classroom
from .class_model import Class
from .subject import Subject
from .attendance_session import AttendanceSession
from .camera import Camera
from .teacher_department import teacher_department_association
from .timetable import Timetable
from .face_embedding import FaceEmbedding
from .attendance_logs import AttendanceLog
from .attendance_record import AttendanceRecord
